version: '3.0'
services:
  redis:
    image: redis
    networks:
      counter-net:
  rocketcounter:
    build: .
    ports:
    - 8085-8086:5000
    networks:
      counter-net:
    volumes:
    - counter-vol:/code

networks:
  counter-net:
volumes:
  counter-vol:
